package linked_list_exercise;

public class Main {

    //CREATE A PROGRAM THAT IMPLEMENTS A PLAYLIST FOR SONGS
    //CREATE A SONG CLASS HAVING TITLE AND DURATION FOR A SONG
    //THE PROGRAM WILL HAVE AN ALBUM CLASS CONTAINING A LIST OF SONGS
    //THE ALBUMS WILL BE STORED IN AN ARRAYLIST
    //SONGS FROM DIFFERENT ALBUMS CAN BE ADDED TO THE PLAYLIST AND WILL APPEAR IN THE LIST IN THE ORDER THEY ARE ADDED


    public static void main(String[] args) {

    }
}
